### ISSUE TITLE
Appears some quotes are missing

### ISSUE THREAD

**Issue by bobsorace** [smitmartijn/Cisco-UCS-Inventory-Script#9]
Is anyone receiving errors running this script like the following?

At D:\UCS_Powershell\UCS-Inventory-Script_2020.ps1:148 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At D:\UCS_Powershell\UCS-Inventory-Script_2020.ps1:5675 char:12
+ </form>    </details-dialog>
+            ~
The '<' operator is reserved for future use.
At D:\UCS_Powershell\UCS-Inventory-Script_2020.ps1:5693 char:46
+       <li class="mr-3 mr-lg-0">"&"copy; 2020 GitHub, Inc.</li>
+                                              ~~~~~~
Unexpected token 'GitHub' in expression or statement.
At D:\UCS_Powershell\UCS-Inventory-Script_2020.ps1:5693 char:52
+       <li class="mr-3 mr-lg-0">"&"copy; 2020 GitHub, Inc.</li>
+                                                    ~
Missing argument in parameter list.
At D:\UCS_Powershell\UCS-Inventory-Script_2020.ps1:5745 char:101
+ ... signed-in" hidden>You signed in with another tab or window. <a href=" ...
+                                                                 ~
The '<' operator is reserved for future use.
At D:\UCS_Powershell\UCS-Inventory-Script_2020.ps1:5746 char:101
+ ... signed-out" hidden>You signed out in another tab or window. <a href=" ...
+                                                                 ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

I found one fix for many of the lines that added single quotes, and have been able to enclose some of the Ampersand characters in double-quotes, but I'm at a point where it seems there is a double-quote missing.

**Comment by smitmartijn** [comment]
It appears you have saved the web page, not the script. Please download scripts from GitHub by using Git, or going to the "Raw" tab and then saving the page. Otherwise, you'll see GitHubs HTML, as you're seeing now.
